### ISSUE TITLE
Remove installation of apt-transport-https from repository recipe

### ISSUE THREAD

**Issue by hrak** [aspyatkin/yarn-cookbook#5]
The installation of apt-transport-https is already taken care of by apt::default, and installing it from `yarn::repository` too triggers a resource cloning warning:

```
Cloning resource attributes for apt_package[apt-transport-https] from prior resource
Previous apt_package[apt-transport-https]: /var/chef/cache/cookbooks/apt/recipes/default.rb:96:in `from_file'
Current  apt_package[apt-transport-https]: /var/chef/cache/cookbooks/yarn/recipes/repository.rb:15:in `from_file' at 1 location:
    - /var/chef/cache/cookbooks/yarn/recipes/repository.rb:15:in `from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```

**Comment by aspyatkin** [comment]
Hello, I'm a little pressed for time right now. Would you please consider submitting a pull request addressing the issue?

**Comment by hrak** [comment]
Sure, here you are!
